### ISSUE TITLE
USCMR-12 failing on must support element MedicationRequest.reported though we support reportedBoolean 

### ISSUE THREAD

**Issue by emily-alt** [onc-healthit/inferno-program#219]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
"USCMR-12: All must support elements are provided in the MedicationRequest resources returned. Could not find reported in the 2 provided MedicationRequest resource(s)."
Our implementation supports the reportedBoolean flag only. This failure came in Inferno 1.4. 

Inferno is installed in-house, using the internal validator

US Core clarified with 3.2 the following:
"The MedicationRequest resource can represent that information is from a secondary source using either a boolean flag or reference in MedicationRequest.reportedBoolean, or a reference using MedicationRequest.reportedReference to Practitioner or other resource.
Although both are marked as must support, **the server systems are not required to support both** a boolean and a reference, but SHALL choose to support at least one of these elements.
The client application SHALL support both elements."
http://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-medicationrequest.html

We understood the Inferno 1.4 release to relax must-support in the same fashion but are failing on reported. 

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.4
* Which browser and version(s) is the bug present on?: 

**Steps to reproduce**
Tell us how to reproduce this issue.
Support reportedBoolean flag
Do NOT support reportedReference

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test. 
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by arscan** [comment]
Thanks for the report.  In a quick look, I think the tests should pass using the v3.1.1 definition with just reportedBoolean, regardless of the additional guidance provided in v3.2.0.  But I'll have the team look more closely to confirm.

In the meantime, could you confirm that you did send a MedicationRequest with a reportedBoolean in USCMR-01 or USCMR-02 by inspecting the http responses?  We can mock up an example too on our side.

**Comment by emily-alt** [comment]
@arscan Thanks for the quick response. Of course the ENV we run Inferno against is down right now, but I did a sanity check on another ENV which has the same code deployed and we're serving up this (only snippet shown):

 "resource": {
                "resourceType": "MedicationRequest",
                "id": "CFFA8272D9C240BAB477B933709F2CD1.2618",
                ...
                "reportedBoolean": false,
                ...
}

I'll attempt to get some ENV attention tomorrow to double confirm this same output in the Inferno linked ENV though we're thinning out quickly for the holidays.

**Comment by emily-alt** [comment]
@arscan Hello again. I can double confirm reportedBoolean is included in JSON body exactly as described in my last comment in the ENV we are running Inferno against.

**Comment by arscan** [comment]
Confirmed on our end this is an issue.  It appears that our 'must support' checking does not count boolean elements filled with a 'false' value, which was not our intention.  If you are able to flip one of those to 'true', it should then pass the test.  We'll work on getting in a fix as quickly as we can.  Thanks for bringing this to our attention!

**Comment by arscan** [comment]
If you are also seeing a fatal error on USCMR-14 with your data, we are looking at that too.

**Comment by emily-alt** [comment]
@arscan We are indeed experiencing a fatal error with USCMR-14, thank you!

Should I close this issue or do you prefer it remains open?

**Comment by arscan** [comment]
Leaving open is good until we resolve the issues officially.  Thanks again for the report and sharing your test data.

**Comment by arscan** [comment]
Hi @emily-alt -- we just released a new version, and deployed it to https://inferno.healthit.gov/ that fixes the two issues mentioned in this ticket:

* `false` values for booleans not counting as evidence of 'must support'
* `contained` references causing test errors

Thanks for the report!  Let me know if you have a chance to try out the update.

Rob

**Comment by emily-alt** [comment]
@arscan We're good on USCMR-12 and a boolean false. Thank you. 

We're still failing on USCMR-14 though it's not related to a Contained resource. Any lingering / known issues with references? It actually seems that *every* reference to a Practitioner or Organization resource is failing with a 403. This is true across all resources, not just MedReq. It's possible it's a scope issue on our end but thought I'd ask. 

![image](https://user-images.githubusercontent.com/75340305/106073652-7d84f500-60d8-11eb-8ace-32bce8b64af1.png)

**Comment by arscan** [comment]
@emily-alt -- I'm sorry for the slow response, I missed this question.  This test is performing http requests for any referenced resource that it finds, and it expects to be granted appropriate scopes to receive those resources (and for the user/patient to have access to that specific resource).  Could you confirm that you request/grant scopes to read those resource types, and that the patient/user has access the specific resources being referenced?

**Comment by emily-alt** [comment]
Thanks @arscan we're good on this one.
