### ISSUE TITLE
Inferno test USCCT-06 failed with the following error - Invalid Resource target type. Found RelatedPerson, but expected one of ([Practitioner, Organization, Patient])(FI-1349)

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#270]
**Subject of the issue**
Inferno Single Patient API CareTeam test USCCT-06 is failing because it does not recognize the Related Person contained resource. The following errors are issued :
Message:
•	CareTeam/A879904FD2FE4B2D90C89FDA84E1285F.LCC: CareTeam.participant[1].member: Invalid Resource target type. Found RelatedPerson, but expected one of ([Practitioner, Organization, Patient])
•	CareTeam/A879904FD2FE4B2D90C89FDA84E1285F.LCC: CareTeam.participant[2].member: Invalid Resource target type. Found RelatedPerson, but expected one of ([Practitioner, Organization, Patient])
According to HL7 FHIR® Release 4, Care Team, http://hl7.org/fhir/R4/careteam.html 
Related Person is one of the types of the member structure.
![image](https://user-images.githubusercontent.com/73243391/114722289-abf19400-9d07-11eb-9ae9-a27269aad255.png)

In our application Related Person is accessed only through the Care Team so it is a contained resource within the Care Team.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.5.0
* Which browser and version(s) is the bug present on?: Chrome
**Steps to reproduce**
Tell us how to reproduce this issue.
Have a person with a relationship to the test patient as Next of Kin. See JSON below how this person is included in the Related Person contained resource. 

Response
Headers
•	content-type: application/json
•	content-length: 5548
•	connection: keep-alive
•	date: Tue, 13 Apr 2021 20:23:20 GMT
•	cache-control: private
•	expires: Thu, 01 Jan 1970 00:00:00 GMT
•	access-control-allow-origin: *
•	access-control-allow-methods: POST, GET, OPTIONS, DELETE
•	access-control-max-age: 3600
•	access-control-allow-headers: x-requested-with, X-Auth-Token, Content-Type, Authorization
•	x-correlation-id: 81247263-f17f-4f21-90da-1c89c739bc31
•	vary: Accept-Encoding
•	x-cache: Miss from cloudfront
•	via: 1.1 a10f8b8edba35e6f4205ea317abf3c49.cloudfront.net (CloudFront)
•	x-amz-cf-pop: IAD50-C2
•	x-amz-cf-id: Tx73L5jPmMlTK-bNTRBtLYGc-Gd5bD0LI_ESbp2DJn6oEvMmrDs9XA==
Body
{
  "resourceType": "Bundle",
  "id": "ab7e3073-8bab-4fc4-bcac-60eedd300a5a",
  "type": "searchset",
  "timestamp": "2021-04-13T16:23:20-04:00",
  "entry": [
    {
      "fullUrl": "https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam/A879904FD2FE4B2D90C89FDA84E1285F.LCC",
      "resource": {
        "resourceType": "CareTeam",
        "id": "A879904FD2FE4B2D90C89FDA84E1285F.LCC",
        "meta": {
          "lastUpdated": "2020-12-16T20:03:37-05:00"
        },
        "status": "active",
        "subject": {
          "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
          "display": "Mcgovern,Astrid Santiago"
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "LA28865-6",
                "display": "Longitudinal care-coordination focused care team"
              }
            ]
          }
        ],
        "participant": [
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "207QA0000X",
                    "display": "Family Medicine"
                  }
                ],
                "text": "Additional Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/4F69EC72C5AA48988E5E73832887E634",
              "display": "Aguilar,Melva Delaine"
            }
          },
          {
            "role": [
              {
                "text": "ZRAut_AutPhysicianG12"
              }
            ],
            "member": {
              "reference": "#203049"
            }
          },
          {
            "role": [
              {
                "text": "HC Proxy - Primary"
              }
            ],
            "member": {
              "reference": "#202549"
            }
          },
          {
            "role": [
              {
                "text": "Patient Centered Medical Home"
              }
            ],
            "member": {
              "reference": "Organization/STF.196052"
            }
          },
          {
            "role": [
              {
                "text": "Primary Physician"
              }
            ],
            "member": {
              "reference": "Practitioner/A06BB34813644589BA7E50D8DDC8EFAA",
              "display": "McFadden,John"
            }
          }
        ],
        "contained": [
          {
            "resourceType": "RelatedPerson",
            "id": "203049",
            "patient": {
              "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
              "display": "Mcgovern,Astrid Santiago"
            },
            "relationship": [
              {
                "text": "ZRAut_AutPhysicianG12"**
              }
            ],
            "name": [
              {
                "use": "official",
                "text": "John,McGovern",
                "family": "John",
                "given": [
                  "McGovern"
                ]
              }
            ]
          },
          {
            "resourceType": "RelatedPerson",
            "id": "202549",
            "patient": {
              "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
              "display": "Mcgovern,Astrid Santiago"
            },
            "relationship": [
              {
                "text": "HC Proxy - Primary"
              }
            ],
            "name": [
              {
                "use": "official",
                "text": "Mcallister,Sathees ",
                "family": "Mcallister",
                "given": [
                  "Sathees "
                ]
              }
            ]
          }
        ],
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Mcgovern,Astrid Santiago<br /><b>Status</b>:active<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA28865-6 <b>Display</b>:Longitudinal care-coordination focused care team<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:207QA0000X <b>Display</b>:Family Medicine <b>Text</b>:Additional Doctor<br /><b>CareTeam Member</b>:Aguilar,Melva Delaine<br /><b>Role</b>:<b>Text</b>:ZRAut_AutPhysicianG12<br /><b>CareTeam Member</b>:John,McGovern<br /><b>Role</b>:<b>Text</b>:HC Proxy - Primary<br /><b>CareTeam Member</b>:Mcallister,Sathees <br /><b>Role</b>:<b>Text</b>:Patient Centered Medical Home<br /><b>Role</b>:<b>Text</b>:Primary Physician<br /><b>CareTeam Member</b>:McFadden,John<br /><br /></div>"
        }
      }
    },
    {
      "fullUrl": "https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam/A879904FD2FE4B2D90C89FDA84E1285F.ENC.29019",
      "resource": {
        "resourceType": "CareTeam",
        "id": "A879904FD2FE4B2D90C89FDA84E1285F.ENC.29019",
        "meta": {
          "lastUpdated": "2020-11-11T20:53:17-05:00"
        },
        "status": "active",
        "subject": {
          "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
          "display": "Mcgovern,Astrid Santiago"
        },
        "encounter": {
          "reference": "Encounter/A879904FD2FE4B2D90C89FDA84E1285F.29019",
          "display": "Inferno,Initial"
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "LA27976-2",
                "display": "Encounter-focused care team"
              }
            ]
          }
        ],
        "participant": [
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "207QA0000X",
                    "display": "Family Medicine"
                  }
                ],
                "text": "Consulting Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/4F69EC72C5AA48988E5E73832887E634",
              "display": "Aguilar,Melva Delaine"
            }
          },
          {
            "role": [
              {
                "text": "Consulting Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/D8A9F3EADBE041688ADD843BBD98CAB0",
              "display": "O'Reilly,Rose"
            }
          },
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "208D00000X",
                    "display": "General Practice"
                  }
                ],
                "text": "Admitting Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/DF2821C049CC47E6A37C6B796DF4CF1D",
              "display": "Godziszewski,Janet Kris"
            }
          },
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "208D00000X",
                    "display": "General Practice"
                  }
                ],
                "text": "Attending Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/DF2821C049CC47E6A37C6B796DF4CF1D",
              "display": "Godziszewski,Janet Kris"
            }
          }
        ],
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Mcgovern,Astrid Santiago<br /><b>Status</b>:active<br /><b>Encounter</b>:Inferno,Initial<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA27976-2 <b>Display</b>:Encounter-focused care team<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:207QA0000X <b>Display</b>:Family Medicine <b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:Aguilar,Melva Delaine<br /><b>Role</b>:<b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:O'Reilly,Rose<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:208D00000X <b>Display</b>:General Practice <b>Text</b>:Admitting Doctor<br /><b>CareTeam Member</b>:Godziszewski,Janet Kris<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:208D00000X <b>Display</b>:General Practice <b>Text</b>:Attending Doctor<br /><b>CareTeam Member</b>:Godziszewski,Janet Kris<br /><br /></div>"
        }
      }
    }
  ],
  "link": [
    {
      "relation": "self",
      "url": "https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam?patient=A879904FD2FE4B2D90C89FDA84E1285F&status=active"
    }
  ]
}

Include:
* The selected test suite: Single Patient API
* The URL of the FHIR server being tested: https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43 (not a public URL)
* The Test ID, if it's a problem with a specific test.: USCCT-06
* Any required configuration options (client ID, client secret, etc.) 
* Anything else needed to make the issue occur. 
* 
**Expected behavior**
Tell us what should happen.
Inferno test USCCT-06 should not fail when Related Person is included in the contained resource.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Test failed with the following errors:
![image](https://user-images.githubusercontent.com/73243391/114722828-202c3780-9d08-11eb-8acc-7b42bb9992cf.png)

**Comment by arscan** [comment]
Thanks @IgLysk00, I believe is an issue where the machine-readable constraints in the StructureDefinitions in US Core v3.1.1 technically state that RelatedPerson is disallowed, even though that wasn't the intent of the authors of the spec.  
 v1.5.0 of Inferno Program Edition updated the version of the HL7 FHIR Validator that it uses, and it seems likely that version is more strict about this than earlier versions about this, which is why we haven't seen this until now.

Note how RelatedPerson isn't listed as an option in the profile itself: https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-careteam.html
![Screen Shot 2021-04-14 at 10 08 12 AM](https://user-images.githubusercontent.com/412901/114724288-6209ad80-9d09-11eb-9186-d13e3f484b4e.png)

There is some language in the guide that [attempts to clarify this](https://www.hl7.org/fhir/us/core/general-guidance.html#referencing-us-core-profiles).  But I don't think that is technically allowed, since a guide can't alter what StructureDefinitions mean.  If they could, then tooling would break, as demonstrated here.

But I think think we should provide an exception for this in our tests, instead of getting too hung up in what the profiles technically say based on current consensus in the machine-readable constraints vs. what the authors wanted to say.  FYI @eHealthedata1 -- let me know if you disagree with my assessment here.  I think this is addressed in v3.2.0?

Thanks!

**Comment by IgLysk00** [comment]
Based on your response it sounds like you agree this should not be a failure and the Inferno team will plan to move forward with an update to make the exception. Is our understanding correct? If yes, any ideas when the fix will be available?

**Comment by yunwwang** [comment]
Hello @IgLysk00, have you tested with the latest release v1.6.1? I suspect this is a validator issue which may have been fixed. Please confirm.

**Comment by IgLysk00** [comment]
I run test again. It failed (see attached). The error is the same as before. We use Inferno 1.6.1. It is still not recognizing contained Related Person data (see example above).
![image](https://user-images.githubusercontent.com/73243391/126550939-9319aab4-a5ae-4100-8e83-4202659cbb4e.png)

**Comment by arscan** [comment]
@yunwwang This is not a validator issue -- it is an acknowledged issue with US Core v3.1.1 because they mistakenly stated that certain reference types were not allowed in the structure defs.  I hope they fixed it in US Core v4.  Can we add an exception coming out of the validator for this very specific thing, for this very specific version of US Core?

**Comment by Healthedata1** [comment]
in 3.1.1 we stated in the narrative here
<http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#referencing-us-core-profiles>
that other references were ok, but the validator is less forgiving.  This
is indeed fixed in 4.0.0.
Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
***@***.***

**Comment by yunwwang** [comment]
> Can we add an exception coming out of the validator for this very specific thing, for this very specific version of US Core? 

We can catch the validator exception but to decide if it is false alarm is not an easy work. Because other than US Core profile, Inferno will need to parse FHIR base profiles too.

**Comment by yunwwang** [comment]
@IgLysk00 Inferno Program v1.8.2 is release. Could you check if your issue has been addressed in this release? Thank you.
